- name: Ensure security packages
  apt: >
    update_cache=yes cache_valid_time=604800
    name=ufw,fail2ban

- name: Allow OpenSSH
  ufw: rule=limit name=OpenSSH

- name: Allow public ports
  ufw: rule=allow port="{{ item.key }}" proto=any comment="{{ item.value | default(omit) }}"
  loop: "{{ firewall_ports_allowed | dict2items }}"
  tags:
    - firewall

- name: Deny public ports
  ufw: rule=deny port="{{ item }}" proto=any comment="{{ item.value | default(omit) }}"
  with_items: "{{ firewall_ports_denied | dict2items }}"
  tags:
    - firewall

- name: Firewall rules
  ufw: rule=allow port="{{ item.port }}" proto="{{ item.proto | default('any') }}" from="{{ item.from | default(omit) }}"
  with_items: "{{ firewall_rules }}"
  tags:
    - firewall

- name: Enable ufw
  ufw: state="{{ enable_firewall | ternary('enabled', 'disabled') }}"

